### ISSUE TITLE
DNS server not removed in modify1cimage.sh

### ISSUE THREAD

**Issue by yol** [dgiese/dustbuilder-script-public#1]
Hi,

this line seems to be intended to remove a fixed DNS server:

https://github.com/dgiese/dustbuilder-script-public/blob/11dc170018272349def3f65af787fdf570cfbc86/modify1cimage.sh#L131

but the generated image has this line in `default.script`:
`     echo "nameserver 114.114.114.114" > $RESOLV_CONF`

so it doesn't work :)

**Comment by dgiese** [comment]
Oh, good catch. That makes me thinking what our idea behind that was... I need to check if removing that nameserver breaks any miio functionality (for people without valetudo)...

**Comment by yol** [comment]
it's not proper/expected behavior for any device to use a random hardcoded DNS server, I guess? but yeah makes sense to check if miio depends on this

**Comment by cornfeedhobo** [comment]
I believe this issue can now be closed, as the script checks for both.
